

POST http://api-registration-videos.onrender.com/videos
Content-Type: application/json

{
  "title": "video 1",
  "description": "Description 8",
  "url": "https://www.youtube.com/embed/glxzwRgXZGM"
}


###


GET http://api-registration-videos.onrender.com/videos


###

PUT http://localhost:3333/videos/d88ead7b-c595-43b0-9700-362a7a623ac0
Content-Type: application/json

{
  "title": "Video 2",
  "description": "Description 2",
  "url": "https://www.youtube.com/watch?v=1"
}

###

DELETE http://api-registration-videos.onrender.com/videos/4dd2d94d-856c-4c23-b109-d732ad4555ca
Content-Type: application/json


###


POST http://localhost:3333/notes
Content-Type: application/json

{
  "title": "IPASS",
  "description": "E uma plataforma na nuvem de low code que simplifica a integracao entre aplicacoes web.",
  "url": "https://www.youtube.com/embed/glxzwRgXZGM",
  "date": "2024-08-31T14:52:00.000Z"
}


###


GET http://localhost:3333/notes


###